// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cmvrnorm
arma::mat cmvrnorm(int n, arma::vec mu, arma::mat Sigma);
RcppExport SEXP RGallery_cmvrnorm(SEXP nSEXP, SEXP muSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP );
        Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP );
        arma::mat __result = cmvrnorm(n, mu, Sigma);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
